### ISSUE TITLE
I’m not sure if I should rename hbw_squeeze_layout.zip or hbw_squeeze_rom.zip to hbw_squeeze.zip? I’m not sure if I should put them in my windows folder or mame-gnw-opt folder?

### ISSUE THREAD

**Issue by ghost** [agg23/fpga-gameandwatch#14]
I’m not sure if I should rename [hbw_squeeze_layout.zip](https://github.com/agg23/fpga-gameandwatch/files/11918114/hbw_squeeze_layout.zip) or [hbw_squeeze_rom.zip](https://github.com/agg23/fpga-gameandwatch/files/12445573/hbw_squeeze_rom.zip) to hbw_squeeze.zip? I’m not sure if I should put them in my windows folder or mame-gnw-opt folder? Can someone please explain what I need to do?

_Originally posted by @AnalogueNintendo in https://github.com/agg23/fpga-gameandwatch/issues/11#issuecomment-1778412471_

**Comment by agg23** [comment]
You have been warned multiple times on multiple different communication methods to stop posting the same thing multiple times in different places. Do not do this again.

See https://github.com/agg23/fpga-gameandwatch/issues/11#issuecomment-1614828078
