### ISSUE TITLE
> > Can someone please explain what I need to do?

### ISSUE THREAD

**Issue by ghost** [agg23/fpga-gameandwatch#15]
> > Can someone please explain what I need to do?
> 
> I have updated the instructions [in the original post](https://github.com/agg23/fpga-gameandwatch/issues/11#issuecomment-1614828078).

I understand that you have updated the instructions in the original post, but the way you worded it made it sound very unclear to me. Can you please explain it to me in more detail and be more specific on what I need to do?

_Originally posted by @AnalogueNintendo in https://github.com/agg23/fpga-gameandwatch/issues/11#issuecomment-1779819178_

**Comment by davewongillies** [comment]
Just [search on archive.org](https://archive.org/search) for `FPGA Optimised Game & Watch Files for MiSTer and Analogue Pocket` and download the prebuilt set

**Comment by ghost** [comment]
I tried that, but the problem is that it doesn’t include all of them especially the 1989 Zelda Game and Watch which is the one I want to play most. The MAME rom files contains ever single Game and Watch game to every be released including the 1989 Zelda Game and Watch. If you can make or find a version of the 1989 Zelda Game and Watch please comment me back the link to the correct website.

**Comment by agg23** [comment]
I was very clear that this behavior would not be tolerated. This is the ninth top level post you have created for this issue, and I believe I have been more than accommodating.

Zelda Game and Watch is not supported, as per the project README; only games that ran on SM510 or SM5a are supported.

Please do not describe how to access copyrighted content anywhere on Github. Your comment has been modified to remove this information.
