### ISSUE TITLE
Rom generator - error message

### ISSUE THREAD

**Issue by Sebbo401** [agg23/fpga-gameandwatch#5]
### Version (or build number)

0.1.0

### Platform (Pocket or MiSTer)

Pocket

### Steps to reproduce

Hi, maybe im just to stupid - but I can't create a rom and always get the same error message:

error: the the following required arguments were not provided:  --output-path <OUTPUT_PATH>

command used:
fpga-gnw-romgenerator --mame-path C:\Users\Johanna\Desktop\ROMS\Game & Watch\windows\Zelda --output-path C:\Users\Johanna\Desktop\ROMS\Game & Watch\windows\ZeldaNew supported

also tried other output paths - same problem.

Any ideas?

### Expected Behavior

rom should be createt

### Actual Behavior

error: the the following required arguments were not provided:  --output-path <OUTPUT_PATH>

**Comment by agg23** [comment]
In most shells paths with spaces must be either escaped, or quoted. Most likely it will work with:
```
fpga-gnw-romgenerator --mame-path "C:\Users\Johanna\Desktop\ROMS\Game & Watch\windows\Zelda" --output-path "C:\Users\Johanna\Desktop\ROMS\Game & Watch\windows\ZeldaNew" supported
```

Please note that this will only function if the `Zelda` directory contains the MAME `artwork` and `roms` directories.

**Comment by Sebbo401** [comment]
Okay, now it's working, but seems like I have the wrong artworks or in they have the wrong format. I get 0 of 89 processed and 89 failed.

**Comment by Sebbo401** [comment]
Okay files and folders are now:

Zelda\artwork\gnw_zelda.zip
Zelda\roms\gnw_zelda.zip

But still the same error:
could not open expected artwork file at C:\\Johanna\\Desktop\\ROMS\\Game & Watch\\windows\\Zelda\\artwork\\txmenpx.zip

txmenpx.zip is different in every of the 89 errors

**Comment by agg23** [comment]
Ok, first, Zelda is not supported by the core at the moment because it's a different CPU type (though the tool will still build it).

As for your actual issue, are you sure there's a file at `C:\Johanna\Desktop\ROMS\Game & Watch\windows\Zelda\artwork\txmenpx.zip`? It's possible the ampersand `&` in your path is causing problems; try a path without that. I doubt this is the issue though

**Comment by Sebbo401** [comment]
Ah! Good to know. Problem is I only wanted to play Zelda - so guess I'll stop trying at this point. But thank you so much for your help and great work!
