### ISSUE TITLE
trspider not in manifest

### ISSUE THREAD

**Issue by espiox** [agg23/fpga-gameandwatch#6]
### Ask a question

Is there a reason why [trspider](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=trspider&search_id=) isn't supported? It seems to just be a clone of [trspacmis](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=trspacmis&search_id=), which does work.

**Comment by agg23** [comment]
That's really weird. There must be a bug in the device name parsing in my manifest builder
