### ISSUE TITLE
Core doesn't display correctly in Dock mode

### ISSUE THREAD

**Issue by davewongillies** [agg23/fpga-gameandwatch#8]
### Version (or build number)

0.1.0

### Platform (Pocket or MiSTer)

Pocket

### Steps to reproduce

- Connect Pocket to Dock
- Launch core
- Launch game. I've tried Oil Panic & Parachute so far

### Expected Behavior

That game isn't cut off

### Actual Behavior

Game output is cut off

![image](https://github.com/agg23/fpga-gameandwatch/assets/69970/91b583d0-7792-40cf-bde0-eb8b2c708d25)

**Comment by agg23** [comment]
The Dock works fine for me (well, that's not true, see below), and I've been testing on it all along.

![Screenshot 2023-06-28 17-28-46](https://github.com/agg23/fpga-gameandwatch/assets/238679/ddb18dcf-cc90-4ca4-bb8e-4f6482910604)

Do you have some special settings selected? That screen looks quite small, is it possible that it's not 720p at minimum (the core runs at 720x720).

Note that I can't confirm that a 720p screen will display the core properly, I just assume it will based on Analogue's scaler.

----

The Dock actually wasn't fine for me, as after the first title I had up on my Pocket when I docked was done, I used the Core Settings menu to switch to another, and it was entirely black. I kept doing this, undocking and redocking (the video would reappear on the Pocket's internal display), even closing and reopening the core. The only thing that fixed it was restarting the Pocket, and I haven't been able to repro.

**Comment by davewongillies** [comment]
Ah yeah that's it. I had my Dock set to 480p as that's the only way for the Dock to output 4:3. Tested at 720p & 1080p and all is good (besides it being a squished 16:9 image but not this core's problem).
